spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/dictionary_db"

    username: djooky
    password: djooky

  flyway:
    baselineOnMigrate: true

  jpa:
    hibernate:
      ddl-auto: update
